spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
spring-api-tools:
  enable-default-pageable: false
