spring:
  datasource:
    url: jdbc:h2:file:./database/testdb;DB_CLOSE_ON_EXIT=FALSE;MODE=MSSQLServer
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
spring-api-tools:
  enable-default-pageable: false
